import type {
  FigmaDeckExportPayload,
  FigmaExportNode,
} from '@/lib/slides/figma-export'

const W = 1920
const H = 1080
/** Minimum width for auto-wrapping text in Figma (avoids one-char columns). */
const TW = 1680
const GUTTER = 120

function t(
  name: string,
  x: number,
  y: number,
  characters: string,
  fontSize: number,
  fill: 'primary' | 'foreground' | 'muted-foreground',
  fontFamily: 'display' | 'sans',
  width: number = TW,
): FigmaExportNode {
  return {
    type: 'TEXT',
    name,
    x,
    y,
    width,
    characters,
    fontSize,
    fill,
    fontFamily,
  }
}

/** English-only partner deck — content mirrors TSX slides; layout is approximate. */
export function buildNetlifyKpDeckFigmaExport(): FigmaDeckExportPayload {
  return {
    version: 1,
    deckId: 'netlify-kp',
    label: 'Build with Netlify · San Salvador',
    frames: [
      {
        name: '01 · Cover',
        width: W,
        height: H,
        children: [
          t('Lockup', GUTTER, 340, 'Ai /abs', 72, 'foreground', 'display', TW),
          t(
            'Series',
            GUTTER,
            460,
            'Build with Netlify · San Salvador',
            28,
            'muted-foreground',
            'display',
            TW,
          ),
          t(
            'Headline',
            GUTTER,
            540,
            "A San Salvador pilot for turning Netlify's platform story into shipped projects.",
            36,
            'foreground',
            'display',
            TW,
          ),
          t(
            'Attribution',
            GUTTER,
            700,
            'Prepared by Ai /abs for the Netlify team.',
            20,
            'muted-foreground',
            'sans',
            720,
          ),
          t('Date', GUTTER, 900, 'May 2026', 11, 'muted-foreground', 'sans', TW),
        ],
      },
      {
        name: '02 · Ai /abs',
        width: W,
        height: H,
        children: [
          t('Eyebrow', GUTTER, 120, 'Who runs this pilot', 12, 'primary', 'sans', TW),
          t(
            'Title',
            GUTTER,
            168,
            "Ai /abs is El Salvador's practical AI lab",
            48,
            'foreground',
            'display',
            TW,
          ),
          t(
            'Body',
            GUTTER,
            300,
            'Ai /abs brings builders into practical rooms: community labs, campus sessions, company trainings, and partner events where people leave with working projects. With Netlify, the next step is clear: help builders experience Netlify as more than hosting.',
            16,
            'muted-foreground',
            'sans',
            TW,
          ),
          {
            type: 'FRAME',
            name: 'Stat 700+',
            x: GUTTER,
            y: 460,
            width: 520,
            height: 240,
            fills: 'background',
            children: [
              t('Value', 32, 32, '700+', 32, 'foreground', 'display', 440),
              t(
                'Label',
                32,
                88,
                'Builders in community',
                10,
                'primary',
                'sans',
                440,
              ),
              t(
                'Note',
                32,
                130,
                'Developers, students, founders, and operators who show up to build.',
                14,
                'muted-foreground',
                'sans',
                440,
              ),
            ],
          },
          {
            type: 'FRAME',
            name: 'Stat 30+',
            x: GUTTER + 540,
            y: 460,
            width: 520,
            height: 240,
            fills: 'background',
            children: [
              t('Value', 32, 32, '30+', 32, 'foreground', 'display', 440),
              t(
                'Label',
                32,
                88,
                'IRL events · past year',
                10,
                'primary',
                'sans',
                440,
              ),
              t(
                'Note',
                32,
                130,
                'Hackathons, meetups, campus labs, and partner sessions with live demos.',
                14,
                'muted-foreground',
                'sans',
                440,
              ),
            ],
          },
          {
            type: 'FRAME',
            name: 'Stat 8',
            x: GUTTER + 1080,
            y: 460,
            width: 520,
            height: 240,
            fills: 'background',
            children: [
              t('Value', 32, 32, '8', 32, 'foreground', 'display', 440),
              t(
                'Label',
                32,
                88,
                'Active partners',
                10,
                'primary',
                'sans',
                440,
              ),
              t(
                'Note',
                32,
                130,
                'Cursor, v0, Codex, and allied teams already trust Ai /abs with the room.',
                14,
                'muted-foreground',
                'sans',
                440,
              ),
            ],
          },
        ],
      },
      {
        name: '03 · Proof 1/2',
        width: W,
        height: H,
        children: [
          t('Eyebrow', GUTTER, 120, 'Proof · 1/2', 12, 'primary', 'sans', TW),
          t(
            'Title',
            GUTTER,
            168,
            'We gather builders in rooms, not webinars',
            48,
            'foreground',
            'display',
            TW,
          ),
          t(
            'Intro',
            GUTTER,
            280,
            'Recent Ai /abs-led sessions with the kind of room Netlify can plug into.',
            14,
            'muted-foreground',
            'sans',
            TW,
          ),
          {
            type: 'RECTANGLE',
            name: 'Photo montage (use Figma capture for source layout)',
            x: GUTTER,
            y: 340,
            width: TW,
            height: 600,
            fill: 'muted',
            cornerRadius: 16,
          },
          t(
            'Captions',
            GUTTER,
            960,
            'Cursor Hackathon · SV — 145 attendees · Cursor Hackathon · GT — 140 · Cafe Cursor — 86 · Cursor Lab · UFG — 75',
            14,
            'muted-foreground',
            'sans',
            TW,
          ),
        ],
      },
      {
        name: '04 · Proof 2/2',
        width: W,
        height: H,
        children: [
          t('Eyebrow', GUTTER, 120, 'Proof · 2/2', 12, 'primary', 'sans', TW),
          t(
            'Title',
            GUTTER,
            168,
            'Same format, different rooms',
            48,
            'foreground',
            'display',
            TW,
          ),
          t(
            'Intro',
            GUTTER,
            280,
            'Meetups, partner labs, and cross-border sessions with laptops open and demos live.',
            14,
            'muted-foreground',
            'sans',
            TW,
          ),
          {
            type: 'RECTANGLE',
            name: 'Photo montage (use Figma capture for source layout)',
            x: GUTTER,
            y: 340,
            width: TW,
            height: 600,
            fill: 'muted',
            cornerRadius: 16,
          },
          t(
            'Captions',
            GUTTER,
            960,
            'Cursor Meetup — 97 · Supabase Meetup — 43 · v0 Prompt to Production · GT — 37',
            14,
            'muted-foreground',
            'sans',
            TW,
          ),
        ],
      },
      {
        name: '05 · Opportunity',
        width: W,
        height: H,
        children: [
          t('Eyebrow', GUTTER, 120, 'Opportunity', 12, 'primary', 'sans', TW),
          t(
            'Title',
            GUTTER,
            168,
            "Netlify's bigger story needs a room",
            48,
            'foreground',
            'display',
            TW,
          ),
          t(
            'Lead',
            GUTTER,
            280,
            'Many builders still think "Netlify = deploy." A local pilot can change that by helping them build with Database, AI Gateway, Functions, and Blobs in one guided session.',
            16,
            'muted-foreground',
            'sans',
            TW,
          ),
          {
            type: 'FRAME',
            name: 'Point hosting',
            x: GUTTER,
            y: 400,
            width: 520,
            height: 280,
            fills: 'background',
            children: [
              t(
                'Card title',
                32,
                32,
                'The hosting label is sticky',
                10,
                'primary',
                'sans',
                440,
              ),
              t(
                'Card body',
                32,
                70,
                'Builders still reduce Netlify to "where I deploy." That makes the newer platform story harder to see.',
                14,
                'muted-foreground',
                'sans',
                440,
              ),
            ],
          },
          {
            type: 'FRAME',
            name: 'Point platform',
            x: GUTTER + 540,
            y: 400,
            width: 520,
            height: 280,
            fills: 'background',
            children: [
              t(
                'Card title',
                32,
                32,
                'The platform expanded',
                10,
                'primary',
                'sans',
                440,
              ),
              t(
                'Card body',
                32,
                70,
                'Database and AI Gateway make Netlify feel like a fuller default for AI apps.',
                14,
                'muted-foreground',
                'sans',
                440,
              ),
            ],
          },
          {
            type: 'FRAME',
            name: 'Point builds',
            x: GUTTER + 1080,
            y: 400,
            width: 520,
            height: 280,
            fills: 'background',
            children: [
              t(
                'Card title',
                32,
                32,
                'Builders trust live builds',
                10,
                'primary',
                'sans',
                440,
              ),
              t(
                'Card body',
                32,
                70,
                'The fastest way to shift perception is to help people ship something in the room.',
                14,
                'muted-foreground',
                'sans',
                440,
              ),
            ],
          },
        ],
      },
      {
        name: '06 · Campaign',
        width: W,
        height: H,
        children: [
          t('Eyebrow', GUTTER, 120, 'Proposal', 12, 'primary', 'sans', TW),
          t(
            'Title',
            GUTTER,
            168,
            'Build with Netlify · city hubs',
            48,
            'foreground',
            'display',
            TW,
          ),
          t(
            'Left lead',
            GUTTER,
            280,
            'Ai /abs can launch the first hub in San Salvador.',
            28,
            'foreground',
            'display',
            800,
          ),
          t(
            'Left body',
            GUTTER,
            360,
            'Ai /abs fills and runs the room. Netlify anchors the product story. Builders leave with deployed URLs, project stories, and work worth amplifying.',
            16,
            'muted-foreground',
            'sans',
            800,
          ),
          {
            type: 'FRAME',
            name: 'What hubs do',
            x: GUTTER + 900,
            y: 280,
            width: 780,
            height: 420,
            fills: 'background',
            children: [
              t(
                'Box eyebrow',
                32,
                32,
                'What hubs do for Netlify',
                10,
                'primary',
                'sans',
                700,
              ),
              t(
                'Bullets',
                32,
                80,
                '• City meetups as repeatable hubs.\n• Credits and swag as activation fuel.\n• Local builders and experts mentoring live.\n• Project recognition and recaps Ai /abs can publish.\n• San Salvador first, then a playbook for more cities.',
                15,
                'muted-foreground',
                'sans',
                700,
              ),
            ],
          },
        ],
      },
      {
        name: '07 · City hub',
        width: W,
        height: H,
        children: [
          t('Eyebrow', GUTTER, 120, 'Model', 12, 'primary', 'sans', TW),
          t(
            'Title',
            GUTTER,
            168,
            'Gather → Activate → Recognize',
            48,
            'foreground',
            'display',
            TW,
          ),
          {
            type: 'FRAME',
            name: 'Step 01',
            x: GUTTER,
            y: 300,
            width: 520,
            height: 280,
            fills: 'background',
            children: [
              t('Step', 32, 32, '01', 12, 'primary', 'sans', 440),
              t('Step title', 32, 64, 'Gather', 20, 'foreground', 'display', 440),
              t(
                'Step body',
                32,
                110,
                'Use the Ai /abs community, campuses, partners, and calendar to fill a credible room.',
                14,
                'muted-foreground',
                'sans',
                440,
              ),
            ],
          },
          {
            type: 'FRAME',
            name: 'Step 02',
            x: GUTTER + 540,
            y: 300,
            width: 520,
            height: 280,
            fills: 'background',
            children: [
              t('Step', 32, 32, '02', 12, 'primary', 'sans', 440),
              t('Step title', 32, 64, 'Activate', 20, 'foreground', 'display', 440),
              t(
                'Step body',
                32,
                110,
                'Pair a live demo with guided build time: Database, AI Gateway, and deploy.',
                14,
                'muted-foreground',
                'sans',
                440,
              ),
            ],
          },
          {
            type: 'FRAME',
            name: 'Step 03',
            x: GUTTER + 1080,
            y: 300,
            width: 520,
            height: 280,
            fills: 'background',
            children: [
              t('Step', 32, 32, '03', 12, 'primary', 'sans', 440),
              t('Step title', 32, 64, 'Recognize', 20, 'foreground', 'display', 440),
              t(
                'Step body',
                32,
                110,
                'Publish a roster, project board, and recap media Netlify can share.',
                14,
                'muted-foreground',
                'sans',
                440,
              ),
            ],
          },
        ],
      },
      {
        name: '08 · June launch',
        width: W,
        height: H,
        children: [
          t('Eyebrow', GUTTER, 120, 'June · Launch', 12, 'primary', 'sans', TW),
          t(
            'Title',
            GUTTER,
            168,
            'Build with Netlify kicks off San Salvador',
            48,
            'foreground',
            'display',
            TW,
          ),
          t(
            'Intro',
            GUTTER,
            272,
            'June tests the playbook: audience quality, pacing, product fit, and recap assets. It also warms up builders ahead of the July Cursor Buildathon sprint.',
            16,
            'muted-foreground',
            'sans',
            TW,
          ),
          t(
            'Bullets',
            GUTTER,
            380,
            '• 3-hour workshop with 50–80 builders on site in San Salvador.\n• Theme: Netlify beyond hosting, from deploys to AI app infrastructure.\n• Guided build with AI Gateway, Netlify Database, and deploy.\n• Optional Netlify cameo live or remote: DevRel, community, or product.\n• Networking time, swag, credits, photography, recap post, and Ai /abs social cadence.',
            15,
            'muted-foreground',
            'sans',
            TW,
          ),
        ],
      },
      {
        name: '09 · July proof',
        width: W,
        height: H,
        children: [
          t('Eyebrow', GUTTER, 120, 'July · Proof', 12, 'primary', 'sans', TW),
          t(
            'Title',
            GUTTER,
            168,
            'Hackathon turns interest into shipped Netlify projects',
            48,
            'foreground',
            'display',
            TW,
          ),
          t(
            'Intro',
            GUTTER,
            300,
            'June introduces the story. July proves adoption: teams, Netlify URLs, products used, demos, and recap content.',
            16,
            'muted-foreground',
            'sans',
            TW,
          ),
          t(
            'Bullets',
            GUTTER,
            400,
            '• Netlify track plus prize slot for Cursor Buildathon (Jul 4–5, Universidad Francisco Gavidia).\n• Teams qualify by deploying on Netlify and using one product beyond hosting.\n• Optional 10-minute kickoff cameo plus two short office-hour windows.\n• Within seven days, Ai /abs shares handles, Netlify URLs, products used, and recap notes.\n• Public showcase board on ailabs.sv showing who shipped what.',
            15,
            'muted-foreground',
            'sans',
            TW,
          ),
        ],
      },
      {
        name: '10 · Value',
        width: W,
        height: H,
        children: [
          t('Eyebrow', GUTTER, 120, 'For Netlify', 12, 'primary', 'sans', TW),
          t(
            'Title',
            GUTTER,
            168,
            'What Netlify gets from the pilot',
            48,
            'foreground',
            'display',
            TW,
          ),
          {
            type: 'FRAME',
            name: 'Win perception',
            x: GUTTER,
            y: 300,
            width: 820,
            height: 200,
            fills: 'background',
            children: [
              t(
                'Card title',
                32,
                32,
                'Perception shifts',
                10,
                'primary',
                'sans',
                740,
              ),
              t(
                'Card body',
                32,
                70,
                'Builders see Netlify as an AI app stack: deploy, Database, AI Gateway, and supporting primitives.',
                14,
                'muted-foreground',
                'sans',
                740,
              ),
            ],
          },
          {
            type: 'FRAME',
            name: 'Win visibility',
            x: GUTTER + 860,
            y: 300,
            width: 820,
            height: 200,
            fills: 'background',
            children: [
              t(
                'Card title',
                32,
                32,
                'Builder visibility',
                10,
                'primary',
                'sans',
                740,
              ),
              t(
                'Card body',
                32,
                70,
                'A named roster and project board showing who shipped, what they built, and which Netlify products they used.',
                14,
                'muted-foreground',
                'sans',
                740,
              ),
            ],
          },
          {
            type: 'FRAME',
            name: 'Win playbook',
            x: GUTTER,
            y: 520,
            width: 820,
            height: 200,
            fills: 'background',
            children: [
              t(
                'Card title',
                32,
                32,
                'Repeatable playbook',
                10,
                'primary',
                'sans',
                740,
              ),
              t(
                'Card body',
                32,
                70,
                'A city-hub format Netlify can reuse after the San Salvador pilot proves the pacing.',
                14,
                'muted-foreground',
                'sans',
                740,
              ),
            ],
          },
          {
            type: 'FRAME',
            name: 'Win operator',
            x: GUTTER + 860,
            y: 520,
            width: 820,
            height: 200,
            fills: 'background',
            children: [
              t(
                'Card title',
                32,
                32,
                'Trusted local operator',
                10,
                'primary',
                'sans',
                740,
              ),
              t(
                'Card body',
                32,
                70,
                'Cursor, v0, and Codex already trust Ai /abs to gather this builder audience.',
                14,
                'muted-foreground',
                'sans',
                740,
              ),
            ],
          },
        ],
      },
      {
        name: '11 · Needs',
        width: W,
        height: H,
        children: [
          t('Eyebrow', GUTTER, 120, 'Light collaboration', 12, 'primary', 'sans', TW),
          t(
            'Title',
            GUTTER,
            168,
            'What we need from Netlify',
            48,
            'foreground',
            'display',
            TW,
          ),
          t(
            'Intro',
            GUTTER,
            280,
            'Ai /abs handles logistics, registration, the room, visuals, and recap. Netlify brings product alignment, lightweight resources, and a few moments of direct presence.',
            16,
            'muted-foreground',
            'sans',
            TW,
          ),
          t(
            'Bullets',
            GUTTER,
            400,
            '• A quick intro video personalized for San Salvador.\n• Credits sized for demos and hackathon finalist teams.\n• Swag for attendees and builders who ship.\n• DevRel or community contact for pacing and AMA prep.\n• Naming approval for "Build with Netlify · San Salvador" or preferred phrasing.',
            15,
            'muted-foreground',
            'sans',
            TW,
          ),
        ],
      },
      {
        name: '12 · Close',
        width: W,
        height: H,
        children: [
          t(
            'Eyebrow',
            GUTTER,
            120,
            'Next conversation',
            12,
            'primary',
            'sans',
            TW,
          ),
          t(
            'Title',
            GUTTER,
            168,
            "Let's align on the pilot in 30 minutes",
            48,
            'foreground',
            'display',
            TW,
          ),
          t(
            'Bullets',
            GUTTER,
            280,
            "• Review the June hub and July buildathon linkage.\n• Lock dates and Netlify's remote or onsite presence.\n• Align the AI Gateway + Database story before Ai /abs markets the pilot.",
            15,
            'muted-foreground',
            'sans',
            TW,
          ),
          t(
            'Pull quote',
            GUTTER,
            420,
            "Let's use San Salvador to prove the format, then turn it into a city-hub playbook Netlify can repeat.",
            17,
            'foreground',
            'sans',
            TW,
          ),
        ],
      },
    ],
  }
}
