/**
 * Regenerates convex/lib/founder_lockup_png_b64.ts from src/assets/founder-lockup-pass.svg.
 * Run: pnpm exec tsx scripts/generate-founder-lockup-png.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const svgPath = join(root, "src/assets/founder-lockup-pass.svg");
const outPath = join(root, "convex/lib/founder_lockup_png_b64.ts");

const svg = readFileSync(svgPath);

/** ~4:1 horizontal lockup; large assets for strong branding in Wallet */
const sizes = [
  { name: "LOGO_1X", width: 400, height: 100 },
  { name: "LOGO_2X", width: 800, height: 200 },
  { name: "LOGO_3X", width: 1200, height: 300 },
] as const;

const parts: Array<string> = [
  `/** Auto-generated by scripts/generate-founder-lockup-png.ts — do not edit by hand. */`,
  `/** Decode in Node-only code: Buffer.from(FOUNDER_LOCKUP_LOGO_1X, "base64") */`,
  ``,
];

for (const { name, width, height } of sizes) {
  const buf = await sharp(svg).resize(width, height).png().toBuffer();
  parts.push(`export const FOUNDER_LOCKUP_${name} = "${buf.toString("base64")}";`);
}

writeFileSync(outPath, `${parts.join("\n")}\n`, "utf8");
console.log("Wrote", outPath);
