/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SlidesRouteImport } from './routes/slides'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MeRouteImport } from './routes/me'
import { Route as LinksRouteImport } from './routes/links'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlidesIndexRouteImport } from './routes/slides.index'
import { Route as ShowcaseIndexRouteImport } from './routes/showcase.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SlidesDeckIdRouteImport } from './routes/slides.$deckId'
import { Route as SignInSsoCallbackRouteImport } from './routes/sign-in_.sso-callback'
import { Route as ShowcaseSubmitRouteImport } from './routes/showcase.submit'
import { Route as ShowcaseSlugRouteImport } from './routes/showcase.$slug'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as CommunitySlugRouteImport } from './routes/community.$slug'
import { Route as AdminWalletRouteImport } from './routes/admin.wallet'
import { Route as AdminLabRouteImport } from './routes/admin.lab'
import { Route as AdminEventsRouteImport } from './routes/admin.events'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SlidesRoute = SlidesRouteImport.update({
  id: '/slides',
  path: '/slides',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlidesIndexRoute = SlidesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlidesRoute,
} as any)
const ShowcaseIndexRoute = ShowcaseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShowcaseRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SlidesDeckIdRoute = SlidesDeckIdRouteImport.update({
  id: '/$deckId',
  path: '/$deckId',
  getParentRoute: () => SlidesRoute,
} as any)
const SignInSsoCallbackRoute = SignInSsoCallbackRouteImport.update({
  id: '/sign-in_/sso-callback',
  path: '/sign-in/sso-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseSubmitRoute = ShowcaseSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => ShowcaseRoute,
} as any)
const ShowcaseSlugRoute = ShowcaseSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ShowcaseRoute,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitySlugRoute = CommunitySlugRouteImport.update({
  id: '/community/$slug',
  path: '/community/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWalletRoute = AdminWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLabRoute = AdminLabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRoute
  '/design-system': typeof DesignSystemRoute
  '/feed': typeof FeedRoute
  '/links': typeof LinksRoute
  '/me': typeof MeRoute
  '/onboarding': typeof OnboardingRoute
  '/partners': typeof PartnersRoute
  '/showcase': typeof ShowcaseRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/slides': typeof SlidesRouteWithChildren
  '/terms': typeof TermsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/lab': typeof AdminLabRoute
  '/admin/wallet': typeof AdminWalletRoute
  '/community/$slug': typeof CommunitySlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/showcase/$slug': typeof ShowcaseSlugRoute
  '/showcase/submit': typeof ShowcaseSubmitRoute
  '/sign-in/sso-callback': typeof SignInSsoCallbackRoute
  '/slides/$deckId': typeof SlidesDeckIdRoute
  '/admin/': typeof AdminIndexRoute
  '/showcase/': typeof ShowcaseIndexRoute
  '/slides/': typeof SlidesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/design-system': typeof DesignSystemRoute
  '/feed': typeof FeedRoute
  '/links': typeof LinksRoute
  '/me': typeof MeRoute
  '/onboarding': typeof OnboardingRoute
  '/partners': typeof PartnersRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/terms': typeof TermsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/lab': typeof AdminLabRoute
  '/admin/wallet': typeof AdminWalletRoute
  '/community/$slug': typeof CommunitySlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/showcase/$slug': typeof ShowcaseSlugRoute
  '/showcase/submit': typeof ShowcaseSubmitRoute
  '/sign-in/sso-callback': typeof SignInSsoCallbackRoute
  '/slides/$deckId': typeof SlidesDeckIdRoute
  '/admin': typeof AdminIndexRoute
  '/showcase': typeof ShowcaseIndexRoute
  '/slides': typeof SlidesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRoute
  '/design-system': typeof DesignSystemRoute
  '/feed': typeof FeedRoute
  '/links': typeof LinksRoute
  '/me': typeof MeRoute
  '/onboarding': typeof OnboardingRoute
  '/partners': typeof PartnersRoute
  '/showcase': typeof ShowcaseRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/slides': typeof SlidesRouteWithChildren
  '/terms': typeof TermsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/lab': typeof AdminLabRoute
  '/admin/wallet': typeof AdminWalletRoute
  '/community/$slug': typeof CommunitySlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/showcase/$slug': typeof ShowcaseSlugRoute
  '/showcase/submit': typeof ShowcaseSubmitRoute
  '/sign-in_/sso-callback': typeof SignInSsoCallbackRoute
  '/slides/$deckId': typeof SlidesDeckIdRoute
  '/admin/': typeof AdminIndexRoute
  '/showcase/': typeof ShowcaseIndexRoute
  '/slides/': typeof SlidesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blog'
    | '/design-system'
    | '/feed'
    | '/links'
    | '/me'
    | '/onboarding'
    | '/partners'
    | '/showcase'
    | '/sign-in'
    | '/sign-up'
    | '/slides'
    | '/terms'
    | '/admin/events'
    | '/admin/lab'
    | '/admin/wallet'
    | '/community/$slug'
    | '/events/$slug'
    | '/showcase/$slug'
    | '/showcase/submit'
    | '/sign-in/sso-callback'
    | '/slides/$deckId'
    | '/admin/'
    | '/showcase/'
    | '/slides/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/design-system'
    | '/feed'
    | '/links'
    | '/me'
    | '/onboarding'
    | '/partners'
    | '/sign-in'
    | '/sign-up'
    | '/terms'
    | '/admin/events'
    | '/admin/lab'
    | '/admin/wallet'
    | '/community/$slug'
    | '/events/$slug'
    | '/showcase/$slug'
    | '/showcase/submit'
    | '/sign-in/sso-callback'
    | '/slides/$deckId'
    | '/admin'
    | '/showcase'
    | '/slides'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/blog'
    | '/design-system'
    | '/feed'
    | '/links'
    | '/me'
    | '/onboarding'
    | '/partners'
    | '/showcase'
    | '/sign-in'
    | '/sign-up'
    | '/slides'
    | '/terms'
    | '/admin/events'
    | '/admin/lab'
    | '/admin/wallet'
    | '/community/$slug'
    | '/events/$slug'
    | '/showcase/$slug'
    | '/showcase/submit'
    | '/sign-in_/sso-callback'
    | '/slides/$deckId'
    | '/admin/'
    | '/showcase/'
    | '/slides/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRoute
  DesignSystemRoute: typeof DesignSystemRoute
  FeedRoute: typeof FeedRoute
  LinksRoute: typeof LinksRoute
  MeRoute: typeof MeRoute
  OnboardingRoute: typeof OnboardingRoute
  PartnersRoute: typeof PartnersRoute
  ShowcaseRoute: typeof ShowcaseRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  SlidesRoute: typeof SlidesRouteWithChildren
  TermsRoute: typeof TermsRoute
  CommunitySlugRoute: typeof CommunitySlugRoute
  EventsSlugRoute: typeof EventsSlugRoute
  SignInSsoCallbackRoute: typeof SignInSsoCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slides': {
      id: '/slides'
      path: '/slides'
      fullPath: '/slides'
      preLoaderRoute: typeof SlidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slides/': {
      id: '/slides/'
      path: '/'
      fullPath: '/slides/'
      preLoaderRoute: typeof SlidesIndexRouteImport
      parentRoute: typeof SlidesRoute
    }
    '/showcase/': {
      id: '/showcase/'
      path: '/'
      fullPath: '/showcase/'
      preLoaderRoute: typeof ShowcaseIndexRouteImport
      parentRoute: typeof ShowcaseRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/slides/$deckId': {
      id: '/slides/$deckId'
      path: '/$deckId'
      fullPath: '/slides/$deckId'
      preLoaderRoute: typeof SlidesDeckIdRouteImport
      parentRoute: typeof SlidesRoute
    }
    '/sign-in_/sso-callback': {
      id: '/sign-in_/sso-callback'
      path: '/sign-in/sso-callback'
      fullPath: '/sign-in/sso-callback'
      preLoaderRoute: typeof SignInSsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase/submit': {
      id: '/showcase/submit'
      path: '/submit'
      fullPath: '/showcase/submit'
      preLoaderRoute: typeof ShowcaseSubmitRouteImport
      parentRoute: typeof ShowcaseRoute
    }
    '/showcase/$slug': {
      id: '/showcase/$slug'
      path: '/$slug'
      fullPath: '/showcase/$slug'
      preLoaderRoute: typeof ShowcaseSlugRouteImport
      parentRoute: typeof ShowcaseRoute
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/$slug': {
      id: '/community/$slug'
      path: '/community/$slug'
      fullPath: '/community/$slug'
      preLoaderRoute: typeof CommunitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/wallet': {
      id: '/admin/wallet'
      path: '/wallet'
      fullPath: '/admin/wallet'
      preLoaderRoute: typeof AdminWalletRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lab': {
      id: '/admin/lab'
      path: '/lab'
      fullPath: '/admin/lab'
      preLoaderRoute: typeof AdminLabRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminEventsRoute: typeof AdminEventsRoute
  AdminLabRoute: typeof AdminLabRoute
  AdminWalletRoute: typeof AdminWalletRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEventsRoute: AdminEventsRoute,
  AdminLabRoute: AdminLabRoute,
  AdminWalletRoute: AdminWalletRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ShowcaseRouteChildren {
  ShowcaseSlugRoute: typeof ShowcaseSlugRoute
  ShowcaseSubmitRoute: typeof ShowcaseSubmitRoute
  ShowcaseIndexRoute: typeof ShowcaseIndexRoute
}

const ShowcaseRouteChildren: ShowcaseRouteChildren = {
  ShowcaseSlugRoute: ShowcaseSlugRoute,
  ShowcaseSubmitRoute: ShowcaseSubmitRoute,
  ShowcaseIndexRoute: ShowcaseIndexRoute,
}

const ShowcaseRouteWithChildren = ShowcaseRoute._addFileChildren(
  ShowcaseRouteChildren,
)

interface SlidesRouteChildren {
  SlidesDeckIdRoute: typeof SlidesDeckIdRoute
  SlidesIndexRoute: typeof SlidesIndexRoute
}

const SlidesRouteChildren: SlidesRouteChildren = {
  SlidesDeckIdRoute: SlidesDeckIdRoute,
  SlidesIndexRoute: SlidesIndexRoute,
}

const SlidesRouteWithChildren =
  SlidesRoute._addFileChildren(SlidesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRoute,
  DesignSystemRoute: DesignSystemRoute,
  FeedRoute: FeedRoute,
  LinksRoute: LinksRoute,
  MeRoute: MeRoute,
  OnboardingRoute: OnboardingRoute,
  PartnersRoute: PartnersRoute,
  ShowcaseRoute: ShowcaseRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  SlidesRoute: SlidesRouteWithChildren,
  TermsRoute: TermsRoute,
  CommunitySlugRoute: CommunitySlugRoute,
  EventsSlugRoute: EventsSlugRoute,
  SignInSsoCallbackRoute: SignInSsoCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
