/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MeRouteImport } from './routes/me'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignInSsoCallbackRouteImport } from './routes/sign-in_.sso-callback'
import { Route as ShowcaseSubmitRouteImport } from './routes/showcase.submit'
import { Route as ShowcaseSlugRouteImport } from './routes/showcase.$slug'
import { Route as CommunitySlugRouteImport } from './routes/community.$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSsoCallbackRoute = SignInSsoCallbackRouteImport.update({
  id: '/sign-in_/sso-callback',
  path: '/sign-in/sso-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseSubmitRoute = ShowcaseSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => ShowcaseRoute,
} as any)
const ShowcaseSlugRoute = ShowcaseSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ShowcaseRoute,
} as any)
const CommunitySlugRoute = CommunitySlugRouteImport.update({
  id: '/community/$slug',
  path: '/community/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/design-system': typeof DesignSystemRoute
  '/feed': typeof FeedRoute
  '/me': typeof MeRoute
  '/onboarding': typeof OnboardingRoute
  '/partners': typeof PartnersRoute
  '/showcase': typeof ShowcaseRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/terms': typeof TermsRoute
  '/community/$slug': typeof CommunitySlugRoute
  '/showcase/$slug': typeof ShowcaseSlugRoute
  '/showcase/submit': typeof ShowcaseSubmitRoute
  '/sign-in/sso-callback': typeof SignInSsoCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/design-system': typeof DesignSystemRoute
  '/feed': typeof FeedRoute
  '/me': typeof MeRoute
  '/onboarding': typeof OnboardingRoute
  '/partners': typeof PartnersRoute
  '/showcase': typeof ShowcaseRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/terms': typeof TermsRoute
  '/community/$slug': typeof CommunitySlugRoute
  '/showcase/$slug': typeof ShowcaseSlugRoute
  '/showcase/submit': typeof ShowcaseSubmitRoute
  '/sign-in/sso-callback': typeof SignInSsoCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/design-system': typeof DesignSystemRoute
  '/feed': typeof FeedRoute
  '/me': typeof MeRoute
  '/onboarding': typeof OnboardingRoute
  '/partners': typeof PartnersRoute
  '/showcase': typeof ShowcaseRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/terms': typeof TermsRoute
  '/community/$slug': typeof CommunitySlugRoute
  '/showcase/$slug': typeof ShowcaseSlugRoute
  '/showcase/submit': typeof ShowcaseSubmitRoute
  '/sign-in_/sso-callback': typeof SignInSsoCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blog'
    | '/design-system'
    | '/feed'
    | '/me'
    | '/onboarding'
    | '/partners'
    | '/showcase'
    | '/sign-in'
    | '/sign-up'
    | '/terms'
    | '/community/$slug'
    | '/showcase/$slug'
    | '/showcase/submit'
    | '/sign-in/sso-callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/blog'
    | '/design-system'
    | '/feed'
    | '/me'
    | '/onboarding'
    | '/partners'
    | '/showcase'
    | '/sign-in'
    | '/sign-up'
    | '/terms'
    | '/community/$slug'
    | '/showcase/$slug'
    | '/showcase/submit'
    | '/sign-in/sso-callback'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/blog'
    | '/design-system'
    | '/feed'
    | '/me'
    | '/onboarding'
    | '/partners'
    | '/showcase'
    | '/sign-in'
    | '/sign-up'
    | '/terms'
    | '/community/$slug'
    | '/showcase/$slug'
    | '/showcase/submit'
    | '/sign-in_/sso-callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BlogRoute: typeof BlogRoute
  DesignSystemRoute: typeof DesignSystemRoute
  FeedRoute: typeof FeedRoute
  MeRoute: typeof MeRoute
  OnboardingRoute: typeof OnboardingRoute
  PartnersRoute: typeof PartnersRoute
  ShowcaseRoute: typeof ShowcaseRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  TermsRoute: typeof TermsRoute
  CommunitySlugRoute: typeof CommunitySlugRoute
  SignInSsoCallbackRoute: typeof SignInSsoCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in_/sso-callback': {
      id: '/sign-in_/sso-callback'
      path: '/sign-in/sso-callback'
      fullPath: '/sign-in/sso-callback'
      preLoaderRoute: typeof SignInSsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase/submit': {
      id: '/showcase/submit'
      path: '/submit'
      fullPath: '/showcase/submit'
      preLoaderRoute: typeof ShowcaseSubmitRouteImport
      parentRoute: typeof ShowcaseRoute
    }
    '/showcase/$slug': {
      id: '/showcase/$slug'
      path: '/$slug'
      fullPath: '/showcase/$slug'
      preLoaderRoute: typeof ShowcaseSlugRouteImport
      parentRoute: typeof ShowcaseRoute
    }
    '/community/$slug': {
      id: '/community/$slug'
      path: '/community/$slug'
      fullPath: '/community/$slug'
      preLoaderRoute: typeof CommunitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ShowcaseRouteChildren {
  ShowcaseSlugRoute: typeof ShowcaseSlugRoute
  ShowcaseSubmitRoute: typeof ShowcaseSubmitRoute
}

const ShowcaseRouteChildren: ShowcaseRouteChildren = {
  ShowcaseSlugRoute: ShowcaseSlugRoute,
  ShowcaseSubmitRoute: ShowcaseSubmitRoute,
}

const ShowcaseRouteWithChildren = ShowcaseRoute._addFileChildren(
  ShowcaseRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BlogRoute: BlogRoute,
  DesignSystemRoute: DesignSystemRoute,
  FeedRoute: FeedRoute,
  MeRoute: MeRoute,
  OnboardingRoute: OnboardingRoute,
  PartnersRoute: PartnersRoute,
  ShowcaseRoute: ShowcaseRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  TermsRoute: TermsRoute,
  CommunitySlugRoute: CommunitySlugRoute,
  SignInSsoCallbackRoute: SignInSsoCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
