/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SponsorKitRouteImport } from './routes/sponsor-kit'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as MeRouteImport } from './routes/me'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommunitySlugRouteImport } from './routes/community.$slug'

const SponsorKitRoute = SponsorKitRouteImport.update({
  id: '/sponsor-kit',
  path: '/sponsor-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitySlugRoute = CommunitySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CommunityRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community': typeof CommunityRouteWithChildren
  '/me': typeof MeRoute
  '/sign-in': typeof SignInRoute
  '/sponsor-kit': typeof SponsorKitRoute
  '/community/$slug': typeof CommunitySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community': typeof CommunityRouteWithChildren
  '/me': typeof MeRoute
  '/sign-in': typeof SignInRoute
  '/sponsor-kit': typeof SponsorKitRoute
  '/community/$slug': typeof CommunitySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/community': typeof CommunityRouteWithChildren
  '/me': typeof MeRoute
  '/sign-in': typeof SignInRoute
  '/sponsor-kit': typeof SponsorKitRoute
  '/community/$slug': typeof CommunitySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community'
    | '/me'
    | '/sign-in'
    | '/sponsor-kit'
    | '/community/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community'
    | '/me'
    | '/sign-in'
    | '/sponsor-kit'
    | '/community/$slug'
  id:
    | '__root__'
    | '/'
    | '/community'
    | '/me'
    | '/sign-in'
    | '/sponsor-kit'
    | '/community/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunityRoute: typeof CommunityRouteWithChildren
  MeRoute: typeof MeRoute
  SignInRoute: typeof SignInRoute
  SponsorKitRoute: typeof SponsorKitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sponsor-kit': {
      id: '/sponsor-kit'
      path: '/sponsor-kit'
      fullPath: '/sponsor-kit'
      preLoaderRoute: typeof SponsorKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/$slug': {
      id: '/community/$slug'
      path: '/$slug'
      fullPath: '/community/$slug'
      preLoaderRoute: typeof CommunitySlugRouteImport
      parentRoute: typeof CommunityRoute
    }
  }
}

interface CommunityRouteChildren {
  CommunitySlugRoute: typeof CommunitySlugRoute
}

const CommunityRouteChildren: CommunityRouteChildren = {
  CommunitySlugRoute: CommunitySlugRoute,
}

const CommunityRouteWithChildren = CommunityRoute._addFileChildren(
  CommunityRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunityRoute: CommunityRouteWithChildren,
  MeRoute: MeRoute,
  SignInRoute: SignInRoute,
  SponsorKitRoute: SponsorKitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
